# Generated by Django 2.0.2 on 2018-04-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='questions',
            field=models.ManyToManyField(blank=True, through='day_app.DayQuestion', to='day_app.Question'),
        ),
    ]
