# Generated by Django 2.0.2 on 2018-04-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day_app', '0002_auto_20180414_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='day_id',
            new_name='day',
        ),
    ]
