# Generated by Django 2.0.2 on 2018-04-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='tags',
            field=models.ManyToManyField(blank=True, to='goal_app.Tag'),
        ),
    ]
