# Generated by Django 2.0.2 on 2018-04-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0004_auto_20180414_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='goal_app.Tag'),
        ),
    ]
