# Generated by Django 2.0.2 on 2018-04-15 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0005_auto_20180414_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='day_app.Day'),
        ),
    ]
