# Generated by Django 2.0.2 on 2018-04-15 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0006_auto_20180416_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='day_app.Day'),
        ),
    ]
