# Generated by Django 2.1 on 2019-04-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0007_auto_20180416_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='is_done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
