# Generated by Django 2.1 on 2019-04-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0008_auto_20190413_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='total_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
