# Generated by Django 2.1 on 2019-04-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0009_auto_20190417_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
